### ISSUE TITLE
Vertical Pod Autoscaler

### ISSUE THREAD

**Issue by thoraxe** [redhat-scholars/openshift-admins-devops#5]
[vpa docs](https://docs.openshift.com/container-platform/4.5/nodes/pods/nodes-pods-vertical-autoscaler.html)

[stress container](https://hub.docker.com/r/polinux/stress)

**Comment by thoraxe** [comment]
```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress-container
        image: polinux/stress
        command: ['stress', '-c', '1']
```

**Comment by thoraxe** [comment]
```YAML
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: stress-recommender
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment 
    name:       stress 
  updatePolicy:
    updateMode: "Auto" 
```
